const GAME_CONFIG = {
	VERSION_GAME: 2,
	BOARD_SIZE: {
		ROWS: 40, 
		COLS: 60,
		CELL: 40,
		BOARD_WIDTH: 60 * 40,
		BOARD_HEIGTH: 40 * 40,
	},

	GENERATE_RULES: {
		TIME_SET_FLY_ITEMS_GENERATION: 30 * 1000,
		TIME_FLY_ITEM_GENERATION: 1000,
		//SIZE_FOG_ON_BOARD: 0.8,
		//MAX_LEVEL_ITEMS_UNDER_FOG: 3,
		RANDOM_TYPE_CHANCE: 0.4,
		LEVEL_ITEMS_INITIAL: 1,
		COUNT_ITEMS_INITIAL: 5,
	},

	ANIMATIONS: { 
		TIME_PUT_FlY_ITEM: 1,
		TIME_PUT_ITEM_FROM_DRAGON: 2,
		TIME_PUT_ITEM_ON_BOARD: 300,
		TIME_PUT_ITEM_ON_BOARD_AFTER_MERGE_TRANSITION: 0.5,
		TIME_REMOVE_ITEM_TRANSITION: 0.3, //s
		TIME_REMOVE_MAGIC_WAY_TRANSITION: 1, //s
		TIME_REMOVE_FOG_TRANSITION: 1, //s
		TIME_FLY_ITEM_TRANSITION: 60 * 4, //s
		SPEED_FLYER: 30,
		SPEED_FLYER_FOR_DIRECTION: 100,
	}, 

	UI: {
		SIZE_GIFT_ON_ITEM_OF_ITEM: 0.25, // 25%
		SIZE_GIFT_ON_ITEM_OF_FLYER: 0.5, // 25%
		TIME_COLLECT_GIFT_FROM_ITEM: 2 * 1000,
	},

	MERGE_RULES: {
		MIN_FOR_MERGE: 3,
		MIN_FOR_BONUS: 5,
		BONUS_MULTIPLIER: 2,
		MAGIC_MERGE_CHANCE: 0.3,
	},

	SHOP: {
		SET_ITEM_FOR_SHOP: ['flowers', 'trees', 'hills', 'water', 'reed'],
		MAX_LEVEL_ITEM_FOR_SHOP: 6,
		PRICE_ITEM: 50, 
		MIN_PRICE_ITEM: 25,
	}
}